### ISSUE TITLE
Perhaps the city should be replaced by prov?

### ISSUE THREAD

**Issue by 180312allison** [psychbruce/bruceR#1]
https://github.com/psychbruce/bruceR/blob/c7c9b26b432609cb908a000c53b0d693ef820637/R/bruceR_plot.R#L201

**Comment by psychbruce** [comment]
My idea is that if you want to draw a city-level map, then it will only draw the border of provinces without "color" or "fill", and plot cities as dots on the map.

**Comment by 180312allison** [comment]
Thanks! I did not consider this.
