### ISSUE TITLE
dplyr 1.0.8

### ISSUE THREAD

**Issue by romainfrancois** [psychbruce/bruceR#11]
We are about to release dplyr 1.0.8 and this currently make this package fail with: 

````
# bruceR

<details>

* Version: 0.7.3
* GitHub: https://github.com/psychbruce/bruceR
* Source code: https://github.com/cran/bruceR
* Date/Publication: 2021-11-05 17:40:01 UTC
* Number of recursive dependencies: 202

Run `cloud_details(, "bruceR")` for more info

</details>

## Newly broken

*   checking examples ... ERROR
    ```
    Running examples in ‘bruceR-Ex.R’ failed
    The error most likely occurred in:
    
    > ### Name: Alpha
    > ### Title: Reliability analysis (Cronbach's alpha and McDonald's omega).
    > ### Aliases: Alpha
    > 
    > ### ** Examples
    > 
    > # ?psych::bfi
    > Alpha(bfi, "E", 1:5)  # "E1" & "E2" should be reverse scored
    Warning: replacing previous import ‘ggplot2::enquo’ by ‘jmvcore::enquo’ when loading ‘jmv’
    Error in jmvcore::enquo(vars) : object 'rlang_enquo' not found
    Calls: Alpha -> <Anonymous> -> <Anonymous> -> <Anonymous>
    Execution halted
    ```

````

This is due to this problem in jmvcore:  https://github.com/jamovi/jmvcore/issues/19 possibly fixed by  https://github.com/jamovi/jmvcore/issues/20

**Comment by psychbruce** [comment]
Thank you for reporting this. I am going to release `bruceR` v0.8.0 to CRAN in the next two weeks, in which `jmv` will be a "Suggests" package rather than an "Imports" one. It seems that the problem you found is related to `jmvcore`. I wonder what should I do next?

**Comment by jonathon-love** [comment]
i'll push an update to `jmvcore` and this should be sorted.

**Comment by romainfrancois** [comment]
Thanks @jonathon-love. @psychbruce feel free to close this issue as `bruceR` is mostly a bystander.

**Comment by jonathon-love** [comment]
jmvcore 2.2 is on its way to CRAN.

> in which jmv will be a "Suggests" package rather than an "Imports" one

haha, yeah, i wouldn't import `jmv` either :P ... every 6 months or so i install it, and the number of dependencies has increased by about a dozen. tinyverse now! although they recently moved `rio` to only be a suggests of `car`, so this may end up halving the number of dependencies ... not sure.
