### ISSUE TITLE
CFA函数缺失一些常用的估计器

### ISSUE THREAD

**Issue by williamlorder** [psychbruce/bruceR#17]
我留意道CFA估计器似乎只有默认的ML估计器，然而其实一些入WLS等估计器也是很常用的，当然还有一些稳健的估计器如MLR等。在lavaan中可以通过输入estimator来更换估计器，我知道CFA是对lavaan结果得封装。这在brucer包中似乎上可以实现。

可能需要添加一些提示告知用户目前使用的是何种估计器。

**Comment by psychbruce** [comment]
谢谢建议，已添加`estimator`参数（since v0.8.5-2）。
