### ISSUE TITLE
条件间试次数量不平衡问题

### ISSUE THREAD

**Issue by sangtianc** [psychbruce/bruceR#19]
您好，很感谢您的付出，bruceR真的是一个非常方便的工具。我最近在使用中遇到一个问题，我有一个两因素被试内的数据，但是其中一个因素的不同水平之间的试次数量是不一样的，这导致我将两个因素都纳入方差分析中时，进行事后检验使用的均值是三个组的均值的均值，和仅计算单个因素的均值是不一样的，得出来的检验结果应该是不准确的。

**Comment by psychbruce** [comment]
你好，

首先，MANOVA函数只能做传统的方差分析，你的情况如果想利用试次level的数据，需要做Linear Mixed Model（可以解决缺失值的问题），例如lmerTest包，而不是用方差分析，也不能仅计算单个因素的均值。

其次，如果是long-format data（一行是一个试次而非一个被试），且希望取不同试次平均值来做被试层面的两因素被试内设计的方差分析，那么无论试次是否有缺失值，MANOVA内部都会进行聚合，你应该会看到提示：“Data are aggregated to mean (across items/trials) if there are >=2 observations per subject and cell. You may use Linear Mixed Model to analyze the data, e.g., with subjects and items as level-2 clusters.”这个仍然会提示并建议你做LMM。

最后，事后检验EMMEANS函数使用了emmeans包，估计的边际均值（estimated marginal means）本来就是取不同条件均值的简单平均，这是方差分析框架下的常规做法（在unbalanced sample size的情况下肯定和单因素拆开看的结果不一样，但单因素的做法肯定是不合理的，忽视了样本不平衡带来的偏差），所以MANOVA和EMMEANS的结果是准确的，仅计算单个因素的均值是不对的。

**Comment by sangtianc** [comment]
谢谢您，我确实忽略了这个提示，非常感谢您的建议
