### ISSUE TITLE
feature request: save APA-style ANOVA output as a word document

### ISSUE THREAD

**Issue by XiaoyuZeng** [psychbruce/bruceR#2]
Hi Bruce, thanks for your effort to make this package! It is terrific and really makes ANOVA easy. 

Would there be any way to save  APA-style ANOVA output as a word document? I did know an r package named apaTables (https://github.com/dstanley4/apaTables) can achieve this goal, but it can not provide effect size and its CI.

It will be great to see how bruceR become better and better!

**Comment by psychbruce** [comment]
Hey, Zeng,

Now `bruceR` has a new function `model_summary()`, which can save results (unstandardized OR standardized coef. AND model fit indices) of most kinds of regression models into a Word or HTML file -- in APA style and ready for academic paper!

Your feature request for ANOVA output may also be satisfied in the near future.

Bruce

**Comment by psychbruce** [comment]
Hi, I have seriously considered the broad usefulness of this functionality and decided not to add a Word output for ANOVA models, because in most cases we do not present ANOVA tables in academic articles. (But regression tables are often required, so `model_summary()` has been developed to do this.) Thanks for your request.

**Comment by XiaoyuZeng** [comment]
> Hi, I have seriously considered the broad usefulness of this functionality and decided not to add a Word output for ANOVA models, because in most cases we do not present ANOVA tables in academic articles. (But regression tables are often required, so `model_summary()` has been developed to do this.) Thanks for your request.

Thanks for considering this!

**Comment by XiaoyuZeng** [comment]
Hi Bao,

I'm so glad to hear that good news. Thanks for your effort!

Best regards,
Xiaoyu

Xiaoyu Zeng

Graduate student, Social and Affective NeuroPharmacology (SANP) Lab

State Key Laboratory of Cognitive Neuroscience and Learning

Beijing Normal University

http://brain.bnu.edu.cn/home/yinama/


Han-Wu-Shuang Bao ***@***.***> 于2021年5月11日周二 下午5:38写道：
