### ISSUE TITLE
三因素混合设计EMMEANS结果和SPSS的GLM结果不一样

### ISSUE THREAD

**Issue by Sisi-Wiciel** [psychbruce/bruceR#20]
近期使用三因素混合设计的SPSS结果和bruceR的结果不一样，其中group是组间，task和con是组内。task因素有3个，做简单效应分析的时候，df2 应该是N-K，N一共是20个，那应该是17个。但是bruceR结果df2是18。不知道是不是我操作错误。过程和测试数据均已上传。
SPSS 语法：
GLM task1con1 task2con1 task3con1 task1con2 task2con2 task3con2 BY group
  /WSFACTOR=con 2 Polynomial task 3 Polynomial 
  /METHOD=SSTYPE(3)
  /POSTHOC=group(LSD BONFERRONI) 
  /PLOT=PROFILE(task*group*con) TYPE=BAR ERRORBAR=CI MEANREFERENCE=YES
  /EMMEANS=TABLES(OVERALL) 
  /EMMEANS=TABLES(con*task*group) COMPAR(task) ADJ(BONFERRONI)
  /PRINT=DESCRIPTIVE ETASQ PARAMETER HOMOGENEITY 
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=con task con*task
  /DESIGN=group.
结果：
![image](https://user-images.githubusercontent.com/21168981/191899780-46c52a4e-1d8d-493d-a42b-5f188acc721e.png)

R 语法：
library(bruceR)
set.wd()
datas <- import(file ='test.sav')
Result <- MANOVA(datas,dvs='task1con1:task3con2',dvs.pattern = 'task(.)con(.)',
       between='group',within=c('task','con'),file='dpd_face.doc') %>%
  #EMMEANS(effect=c('task','con'),by='group')
  EMMEANS(effect='task',by=c('group','con'),model.type = "multivariate")
结果：
![image](https://user-images.githubusercontent.com/21168981/191899822-ad521f33-b26a-41f0-83c7-bff0da0d301b.png)
测试数据：
[test.zip](https://github.com/psychbruce/bruceR/files/9631013/test.zip)

**Comment by Sisi-Wiciel** [comment]
好像SPSS的语法粘贴上来有问题，以下是截图
![image](https://user-images.githubusercontent.com/21168981/191900343-d13fb9ee-67b6-4df9-baaf-679a97b5ac6e.png)

**Comment by psychbruce** [comment]
你好，应该是Open Science群里提问的那位同学吧，我这里再整理一下。

存在两个问题：
1. SPSS分析简单效应，不要看Multivariate Tests那部分表格，而是要看SPSS MANOVA语句分析结果中，Analysis of Variance -- Design部分下的“Tests involving ...”，详见[SPSS方差分析中的简单效应检验：完整教程](https://zhuanlan.zhihu.com/p/30037168)。
2. 方差分析的误差自由度并不是N - K，我不知道这个说法是哪里来的，这是不对的。误差df的计算规律是：(被试间水平数) × (被试内水平数 - 1) × (n - 1)，其中n是各组被试量均衡情况下的“小单元格内”的被试量（≠ 总被试量）。同时，简单效应检验与方差分析共享相应部分的误差项。详见舒华老师的《心理与教育研究中的多因素实验设计》一书。在你给的test.sav数据里，针对要计算的task被试内因素的简单效应，“小单元格被试量” n = 10，group被试间水平数 = 2，con被试内水平数 = 2，所以df2 = 2 * (2 - 1) * (10 - 1) = 18。

所以，bruceR的计算结果是正确的。
