### ISSUE TITLE
PROCESS()的模型描述

### ISSUE THREAD

**Issue by zuoyouheng** [psychbruce/bruceR#22]
Bruce先生您好，在PROCESS()的输出结果中的模型编号一行
`PROCESS Model Code : 14 (Hayes, 2018; www.guilford.com/p/hayes3)`
中的网址已经失效了，现在打开它只会跳转到*Introduction to Mediation, Moderation, and Conditional Process Analysis*这本书的购书页面，我不知道这个网页原本的内容是什么，所以这个模型编号就没有提供实际的参考信息。
以及，bruceR真的是一个非常实用和便捷的工具，谢谢你的贡献。

**Comment by psychbruce** [comment]
你好，这个链接本来就是指向这本书的，是一个缩短处理的链接，所以没有任何问题（由于版权，我不可能把原书直接共享出来，需要用户自行搜索和阅读）。PROCESS Model Code是Hayes在书中定义的路径模型的编号，在`bruceR`中其实没有实际参考价值，只是为知道模型编号的用户提供一个对照；如果用户不知道模型编号也没关系，忽略这个编号就可以了。`bruceR`的`PROCESS()`的使用并不需要知道模型编号，而只需要定义变量`x`、`y`、`meds`、`mods`等，因此更直接。

关于不同模型、不同软件之间的对比，详见这个PDF：
https://github.com/psychbruce/bruceR/blob/main/note/PROCESS-bruceR-SPSS.pdf
