### ISSUE TITLE
关于MANOVA()函数无法处理列名包含两位数的数据

### ISSUE THREAD

**Issue by mxjjk** [psychbruce/bruceR#24]
想问一个关于MANOVA()函数的问题，我的实验是一个重复测量两因素的三因素方差分析。在我处理我的宽数据的时候，我发现当我的列名是（sec_3_t1，sec_3_t6，sec_9_t1，sec_9_t6）的时候能正常返回结果，但是列名变成（sec_4_t1，sec_4_t6，sec_10_t1，sec_10_t6）的时候就不能正常运行了。报错原因是：Failed to perform MANOVA.。想问一下是否是因为列名称里出现了两位数就不能正常运行函数。
我的代码部分如下
MANOVA(data = data,
           dvs=paste(c(dvs[1], dvs[4]), collapse = ":"),
           dvs.pattern="sec_(.)_(t.)",
           between="disease",
           within=c("section", "time"),
           file = file.path(wide_format_dir, basename(file)))
报错如下：
Note:
dvs="sec_4_t1:sec_10_t6" is matched to variables:
sec_4_t1, sec_4_t6, sec_10_t1, sec_10_t6

Error: 
    Failed to perform MANOVA.
    Please follow the correct usage.
    See: help(MANOVA)

数据的前五行格式如下
disease	sec_4_t1	  sec_4_t6	        sec_10_t1	         sec_10_t6
0	0.148010408	0.240479665	0.137365773	0.162679725
0	0.164722607	0.208784311	0.155697349	0.131884651
0	0.128987875	0.155202186	0.123803308	0.107702303
0	0.14838339	0.212513358	0.146451598	0.19047774
0	0.134528406	0.208767676	0.108596354	0.130336021

**Comment by psychbruce** [comment]
是完全可以处理的，请仔细阅读帮助文档：
![image](https://github.com/psychbruce/bruceR/assets/34391475/28b8bcf2-3e19-47ce-9b36-d40a88b69afc)
