### ISSUE TITLE
关于EMMEANS()分析结果能否输出成文本的问题

### ISSUE THREAD

**Issue by mxjjk** [psychbruce/bruceR#25]
我现在希望能将简单效应分析和多重比较的结果也以文本的形式输出。但是现在只在MANOVA()函数里找到了file关键字，输出出来的内容也只包含了方差分析的部分，帮助文档里面的EMMEANS()这个函数没有相关的关键词。
因为课题要处理的数据比较多，所以如果能整合到一个文档里输出会节省很多功夫，因为没有找到这个功能所以打扰一下作者，不知道有没有这个功能？

**Comment by psychbruce** [comment]
`EMMEANS()`不提供Word输出功能，因为要输出的表格太多了。

建议了解使用R Markdown进行自动化结果整理，例如新建一个.Rmd文件：

![image](https://github.com/psychbruce/bruceR/assets/34391475/db9a7f35-7f45-44b6-9866-9ea5d7437346)

Knit一下可以直接把所有代码和Console输出的结果输出到一个Word文档（.docx）：

![image](https://github.com/psychbruce/bruceR/assets/34391475/b0e40aff-04f1-4680-a7b7-55f5396dc3cc)
（省略一部分截图）
![image](https://github.com/psychbruce/bruceR/assets/34391475/2b9840ce-9591-4428-9fb2-515daa6a9ead)

另外还可以输出到PDF或HTML，只需要修改output：

`output: pdf_document`
或
`output: html_document`

或者：

![image](https://github.com/psychbruce/bruceR/assets/34391475/2e99b9b7-010b-4ed9-b34f-b4948194851a)

具体请自行查阅R Markdown的用法，有更灵活的设置。

（注：此Issue将保留不关闭，以供其他用户参考）

**Comment by mxjjk** [comment]
感谢作者的回复，我后来用sink()将内容输出成.txt了，也能做到想用的效果

**Comment by psychbruce** [comment]
对，`sink()`也可以。更推荐用R Markdown，可以同时输出代码、结果、图表、非代码的文字描述、多级标题等等（多种内容的混排），也可以更美观一些。我现在自己的研究项目一般都用.Rmd（而不是.R）写代码和整理结果，方便自己和其他人查看。
