### ISSUE TITLE
请问做完PROCESS函数的中介分析，尤其是多中介变量的中介分析，如何进行可视化

### ISSUE THREAD

**Issue by nkchangshu** [psychbruce/bruceR#27]
请问做完PROCESS函数的中介分析，尤其是多中介变量的中介分析，如何进行可视化，用哪个函数可以做？

**Comment by psychbruce** [comment]
你好，bruceR并不提供中介分析的作图函数，用户需要自己画，比如用PPT，也不难

**Comment by nkchangshu** [comment]
好的，谢谢您，感谢

发件人：Han-Wu-Shuang Bao ***@***.***>
发送日期：2023-11-02 09:26:00
收件人：psychbruce/bruceR ***@***.***>
抄送人："飞时过" ***@***.***>,Author ***@***.***>
主题：Re: [psychbruce/bruceR] 请问做完PROCESS函数的中介分析，尤其是多中介变量的中介分析，如何进行可视化 (Issue #27)

你好，bruceR并不提供中介分析的作图函数，用户需要自己画，比如用PPT，也不难
