### ISSUE TITLE
EMMEANS是否只支持宽数据？

### ISSUE THREAD

**Issue by Tongzhao9417** [psychbruce/bruceR#28]
您好！我在使用bruceR时，用MANOVA计算单因素重复测量方差分析的结果，数据输入的是长数据，计算一切正常。但是当我把model输入到EMMEANS，并指定by为被试内因素时，会报错提示：“There are no factors to test”。请问是因为我输入数据为长数据的原因吗？谢谢您！

**Comment by psychbruce** [comment]
MANOVA支持长数据和宽数据，内部实际上会统一转换为长数据，所以长数据完全没有问题。你说的问题在于，单因素重复测量，在使用EMMEANS时本来就只能指定effect参数（自变量），而根本没有by因素（调节变量）。只有多因素才能指定by（调节变量）。所以显然，你会看到报错。当然你这个报错本身意思是没有指定effect参数，所以“没有因素可检验”。effect是无论如何必须设定的，不管有没有by。

请多阅读帮助文档。

https://psychbruce.github.io/bruceR/reference/EMMEANS.html

```
MANOVA(within.1, dvs="A1:A4", dvs.pattern="A(.)", within="A") %>%
  EMMEANS("A")
```

**Comment by Tongzhao9417** [comment]
> MANOVA支持长数据和宽数据，内部实际上会统一转换为长数据，所以长数据完全没有问题。你说的问题在于，单因素重复测量，在使用EMMEANS时本来就只能指定effect参数（自变量），而根本没有by因素（调节变量）。只有多因素才能指定by（调节变量）。所以显然，你会看到报错。当然你这个报错本身意思是没有指定effect参数，所以“没有因素可检验”。effect是无论如何必须设定的，不管有没有by。
> 
> 请多阅读帮助文档。
> 
> https://psychbruce.github.io/bruceR/reference/EMMEANS.html
> 
> ```
> MANOVA(within.1, dvs="A1:A4", dvs.pattern="A(.)", within="A") %>%
>   EMMEANS("A")
> ```

多谢！是我理解的有些问题：我应该在effect里设置单因素的变量，而不是MANOVA里的“因变量”。谢谢您的回复！
