### ISSUE TITLE
Can't install bruceR

### ISSUE THREAD

**Issue by waa8128** [psychbruce/bruceR#3]
I cannot install bruceR. The warning seemed like Bug #04, but the soluation of Bug#04 was not work.
I had updated the R to the latest version 4.0.2, but the error still remained.

> devtools::install_github("psychbruce/bruceR")
Downloading GitHub repo psychbruce/bruceR@HEAD
  
   checking for file 'C:\Users\THINK\AppData\Local\Temp\RtmpSoK5KO\remotes48d859227c82\psychbruce-bruceR-eded61e/DESCRIPTION' ...
√  checking for file 'C:\Users\THINK\AppData\Local\Temp\RtmpSoK5KO\remotes48d859227c82\psychbruce-bruceR-eded61e/DESCRIPTION'
-  preparing 'bruceR':
   checking DESCRIPTION meta-information ...
  
   checking DESCRIPTION meta-information ... 
  
√  checking DESCRIPTION meta-information

-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'bruceR_0.5.1.tar.gz'

Installing package into ‘C:/Users/THINK/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'bruceR' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'emmeans'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
停止执行
ERROR: lazy loading failed for package 'bruceR'
* removing 'C:/Users/THINK/Documents/R/win-library/4.0/bruceR'
错误: Failed to install 'bruceR' from GitHub:
  (由警告转换成)installation of package ‘C:/Users/THINK/AppData/Local/Temp/RtmpSoK5KO/file48d823453f6b/bruceR_0.5.1.tar.gz’ had non-zero exit status
>

**Comment by psychbruce** [comment]
Hi, please look at these two lines in the output:
```
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
there is no package called 'emmeans'
```
There might be some unknown bugs when installing the `emmeans` package.
Just run `install.packages("emmeans")` and then re-install `bruceR`.

**Comment by waa8128** [comment]
it works, thank you.
