### ISSUE TITLE
Add Option to Omit Zero-Frequency Categories in Freq()

### ISSUE THREAD

**Issue by linem7** [psychbruce/bruceR#31]
Hi,

I would like to ask if it would be possible to add a new feature to the Freq() function to omit categories with zero frequencies. This would simplify the output, especially for datasets imported from SPSS with many value labels.

Thank you for considering this request!

Best regards,
Lin

**Comment by psychbruce** [comment]
Thank you for your suggestion. Zero-frequency can be meaningful for users to check their data (i.e., displaying categories as they are but not hiding some of them) and can be easily removed from MS Word table output. Most situations in practice do not have zero-frequencies. It is also users' responsibility to preprocess their data properly before using such a function. So I am not convinced that it is a highly necessary addition to the features.

**Comment by psychbruce** [comment]
Thank you for your suggestion. Zero-frequency can be meaningful for users to check their data (i.e., displaying categories as they are but not hiding some of them) and can be easily removed from MS Word table output. Most situations in practice do not have zero-frequencies. It is also users' responsibility to preprocess their data properly before using such a function. So I am not convinced that it is a highly necessary addition to the features.
