### ISSUE TITLE
Export only first table to Word Doc

### ISSUE THREAD

**Issue by chloevoyer** [psychbruce/bruceR#34]
Hi, 

Is there a way I could export only the first table to a word doc using the Corr function, that is "Table 1. Descriptive Statistics and Correlation Matrix"? 

I would like to exclude table from the output: 
Table 2. Correlations and 95% Confidence Intervals.

**Comment by psychbruce** [comment]
Hi, Sorry that the Corr() output for MS Word is fixed for full information and cannot be modified. I believe it is quite simple to delete the Table by hand in MS Word, and users can copy and paste the Table they want from the Word output to their article. So please do that by hand. Thanks.

**Comment by chloevoyer** [comment]
This is for an automated workflow and the idea is to avoid manual manipulation.

**Comment by psychbruce** [comment]
I understand, but as a package designer I have to consider what most users may need and what features are necessary to add an argument for a function.
