### ISSUE TITLE
Exact P value from PROCESS

### ISSUE THREAD

**Issue by professorteschner** [psychbruce/bruceR#35]
Hello, 

I am trying to figure out how to obtain exact p-values from a moderated mediation model I ran. Is there a way to do this?

****************** PART 1. Regression Model Summary ******************

PROCESS Model Code : 4 (Hayes, 2018; www.guilford.com/p/hayes3)
PROCESS Model Type : Simple Mediation
-    Outcome (Y) : substance_t2
-  Predictor (X) : dissonance
-  Mediators (M) : mental_t2r
- Moderators (W) : -
- Covariates (C) : -
-   HLM Clusters : -

All numeric predictors have been grand-mean centered.
(For details, please see the help page of PROCESS.)

Formula of Mediator:
-    mental_t2r ~ dissonance
Formula of Outcome:
-    substance_t2 ~ dissonance + mental_t2r

CAUTION:
  Fixed effect (coef.) of a predictor involved in an interaction
  denotes its "simple effect/slope" at the other predictor = 0.
  Only when all predictors in an interaction are mean-centered
  can the fixed effect denote the "main effect"!
  
Model Summary

───────────────────────────────────────────────────────────────
             (1) substance_t2  (2) mental_t2r  (3) substance_t2
───────────────────────────────────────────────────────────────
(Intercept)    4.324 ***         3.078 ***       4.324 ***     
              (0.200)           (0.036)         (0.199)        
dissonance     1.185 ***        -0.851 ***       0.550         
              (0.216)           (0.039)         (0.338)        
mental_t2r                                      -0.746 *       
                                                (0.308)        
───────────────────────────────────────────────────────────────
R^2            0.086             0.601           0.102         
Adj. R^2       0.083             0.599           0.097         
Num. obs.    324               324             324             
───────────────────────────────────────────────────────────────
Note. * p < .05, ** p < .01, *** p < .001.

************ PART 2. Mediation/Moderation Effect Estimate ************

Package Use : ‘mediation’ (v4.5.0)
Effect Type : Simple Mediation (Model 4)
Sample Size : 324
Random Seed : set.seed(1)
Simulations : 5000 (Bootstrap)

Running 5000 simulations...
Indirect Path: "dissonance" (X) ==> "mental_t2r" (M) ==> "substance_t2" (Y)
─────────────────────────────────────────────────────────────
               Effect    S.E.     z     p       [Boot 95% CI]
─────────────────────────────────────────────────────────────
Indirect (ab)   0.635 (0.325) 1.952  .051 .   [ 0.023, 1.286]
Direct (c')     0.550 (0.419) 1.313  .189     [-0.265, 1.359]
Total (c)       1.185 (0.221) 5.351 <.001 *** [ 0.755, 1.620]
─────────────────────────────────────────────────────────────
Percentile Bootstrap Confidence Interval
(SE and CI are estimated based on 5000 Bootstrap samples.)

Note. The results based on bootstrapping or other random processes
are unlikely identical to other statistical software (e.g., SPSS).
To make results reproducible, you need to set a seed (any number).
Please see the help page for details: help(PROCESS)
Ignore this note if you have already set a seed. :)

**Comment by psychbruce** [comment]
Hi, exact p values are directly provided only for PART 2. For p values in PART 1, users can find regression models from the returned object (saving PROCESS to an R object and finding what elements are included in it). The function output does not provide further details for PART 1 because it was designed mainly for PART 2.

**Comment by professorteschner** [comment]
The below did allow me to extract it easily. 

model_summaries <- lapply(df, summary)

for (i in seq_along(model_summaries)) {
  cat("Summary for Model", i, ":\n")
  print(model_summaries[[i]])
  cat("\n")
}
