### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Chauncy-Fang** [psychbruce/bruceR#5]
is this package can only be installed in R version>4.0.0?

**Comment by psychbruce** [comment]
Yes, as R has changed in many aspects before and after v4.0.0, now bruceR requires R version >= 4.0.0 (see https://github.com/psychbruce/bruceR/blob/master/DESCRIPTION for this requirement). The main reason is that **more and more R packages (depended on by bruceR) no longer support R versions < 4.0.0**, and bruceR has to follow this. So just **update your R to the latest version**.
