### ISSUE TITLE
A Question 

### ISSUE THREAD

**Issue by pomang-211** [psychbruce/bruceR#7]
I think this is a good job. But I have some questions. For example,this package can not installed。

install.packages("bruceR")

Warning in install.packages :
  package ‘bruceR’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by psychbruce** [comment]
Thanks. On 2021-03-19, `bruceR` was formally published on CRAN: https://CRAN.R-project.org/package=bruceR

From now on, all users can install `bruceR` either using `install.packages("bruceR")` (for the latest **released version** on CRAN) or using `devtools::install_github("psychbruce/bruceR")` (for the latest **development version** on GitHub).
